substitutions:
  power_pin: GPIO4     # Пин для кнопки питания (через транзистор)
  reboot_pin: GPIO6    # Пин для кнопки Reboot (через транзистор BM548)
  status_pin: GPIO8
  api_key: !secret power_control_api
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_password: !secret ap_password
  ota_password: !secret power_control_ota

esphome:
  name: pc-power-control
  friendly_name: "PC Control"


esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: ${api_key}
  reboot_timeout: 0s

ota:
  platform: esphome
  password: "xxxx"     # пароль для OTA


wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "PC-Control-Fallback"
    password: ${ap_password}

web_server:
  port: 80


output:
  - platform: gpio
    pin: ${power_pin}
    id: power_button_output

  - platform: gpio
    pin: 
      number: ${reboot_pin}
      mode: output
      inverted: false
    id: reboot_button_output

binary_sensor:
  - platform: gpio
    pin:
      number: ${status_pin}
      mode: input
    name: "PC Status"
    device_class: power
    id: pc_status

# Кнопки управления питанием
button:
  - platform: template
    name: "Turn On PC"
    icon: "mdi:power"
    on_press:
      - output.turn_on: power_button_output
      - delay: 500ms
      - output.turn_off: power_button_output

  - platform: template
    name: "Soft Shutdown PC"
    icon: "mdi:power-standby"
    on_press:
      - output.turn_on: power_button_output
      - delay: 1s
      - output.turn_off: power_button_output

  - platform: template
    name: "Force Shutdown PC"
    icon: "mdi:power-off"
    on_press:
      - output.turn_on: power_button_output
      - delay: 5s
      - output.turn_off: power_button_output

  - platform: template
    name: "Reboot PC"
    icon: "mdi:restart-alert"
    on_press:
      - output.turn_on: reboot_button_output
      - delay: 500ms
      - output.turn_off: reboot_button_output

# Мониторинг состояния
sensor:
  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
