# Базовая конфигурация ESP32-C3
esphome:
  name: pc-power-control
  friendly_name: "PC Control"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Настройка UART для связи с хостом
uart:
  id: uart_bus
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1

logger:
  level: DEBUG  # Включаем подробное логирование
  baud_rate: 115200

# Кнопки управления ВМ
button:
  # Управление ВМ
  - platform: template
    name: "Start VM"
    icon: "mdi:play"
    entity_category: "config"
    on_press:
      - logger.log: "VM START command"
      - uart.write: "start\n"

  - platform: template
    name: "Stop VM"
    icon: "mdi:stop"
    entity_category: "config"
    on_press:
      - logger.log: "VM STOP command"
      - uart.write: "stop\n"

  - platform: template
    name: "Reboot VM"
    icon: "mdi:restart"
    entity_category: "config"
    on_press:
      - logger.log: "VM REBOOT command"
      - uart.write: "reboot\n"

  - platform: template
    name: "Force Stop VM"
    icon: "mdi:power-off"
    entity_category: "config"
    on_press:
      - logger.log: "VM FORCE STOP command"
      - uart.write: "destroy\n"
